### ISSUE TITLE
Day 2

### ISSUE THREAD

**Issue by junesvibes** [junesvibes/100Challenge#1]
Can't figure out the issue with the indentions

**Comment by KristoforL** [comment]
Hey I added some comments and fixed it up for you. I hope that there are not logic errors for what you expected but the few indention errors and typos in your code have been resolved:

 space= "\n"
print("Welcome to my First Game!")

name= input("What is your name? ")
age= input("What is your age? ")


health = 10

print("You are starting with", health, "heatlh.")

if age >= "18":
    print("You are old enough to play!")
    wants_to_play= input("Do you want to play? ").lower()
    #Since you lowered 'wants_to_play', the if statement can be compared to just "yes"'. This did not cause an error but just 
    something I saw in reviewing to understand the flow of your code. I did not change this but wanted you understand the 
    logic
    if wants_to_play == "Yes" or "yes":
        #It may be better to hard code this space print into your print statements. Better than typing more for a next line 
        instead of printing out space. Remember the less lines of code you have to read the faster and efficient your code.
        print(space)
        print("Let's play! ")
        
        left_or_right = input("First choice... Left of Right? ")
        #Make sure that you set this as a comparison "==", and not set "=". This was causing an error in your code as the IDE 
        did not understand what you were doing
        if left_or_right == "left":
            ans = input("Nice, you follow the path and reach a lake... Do you swim across or go around (across/around)? ")

            #Do not forget to set your quotations around input since they will be read as strings. That was also causing an error
            if ans == "around":
                print("You went around and reached the other side of the lake")
            
            #Do not forget to set your quotations around input since they will be read as strings. That was also causing an error
            elif ans == "across":
                print("You managed to get across, but were bit by a fish and lost 5 health. ")
                health -= 5

            else:
                print("You lost...")
        else:
            print("You fell down a lost...")

    else:
        print("Cya...")
elif age >="13":
    print("You can play with supervision. ")
else:
    print("You are not old enough to play...")
